<?php 

/**
* Implements of hook_menu().
*/
function user_filter_menu() {
  $items['user/info/ajax/%'] = array(
    'page callback' => 'user_filter_info',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access arguments' => array('access user profiles'),
    'delivery callback' => 'user_filter_ajax_callback',
    'file' => 'user_filter.page.inc',
  );
  return $items;
}

function user_filter_theme() {
  $module_path = drupal_get_path('module', 'user_filter');
  $base = array(
    'path' => "$module_path/theme",   
  );
  return array(
    'user_info' => $base + array(
      'variables' => array(
        'user' => NULL,
        'cu' => NULL,
      ),
      'template' => 'user_info',
    ),
  );
}

/**
 * Callback for view user tip
 */
function user_filter_ajax_callback($profile){
  global $user;
  $content = theme('user_info', array('user' => $profile, 'cu' => $user));
  print $content;
  drupal_page_footer();
}

/**
 * Implements hook_entity_info_alter()
 * Add view mode 'user_info' for users
 */
function user_filter_entity_info_alter(&$entity_info){
  $entity_info['user']['view modes']['user_info'] = array(
    'label' => t('User info'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_filter_info()
 */
function user_filter_filter_info() {
  $filters = array();
  $filters['user_filter'] = array(
    'title' => t('User filter'),
    'description' => t('View user info by "@username"'),
    'process callback' => 'user_filter_filter_process',
    'cache' => FALSE,
  );
  return $filters;
}

/**
 * Filter process
 */
function user_filter_filter_process($text, $filter, $format) {
  if(!empty($text)) {
    $users = user_filter_mention($text);
    if(!empty($users)){
      foreach($users as $user){
        $text = preg_replace('/@' . $user->name . '/', '<span class="user_filter" data-user="' . $user->name . '">@' . $user->name . '</span>', $text);
      }
    }
    return $text;
  }
  else{
    return $text;
  }
}

function user_filter_mention($text){
  if(!empty($text)) {
    $users = array();
    preg_match_all('/[@][\w\d]+/', $text, $matches);
    foreach($matches[0] as $match){
      $name = drupal_substr($match, 1, $length = NULL);
      $user = user_load_by_name($name);
      if(is_object($user)){
        $users[] = $user;
      }
    }
    return $users;
  }
}

/**
 * Implements hook_init()
 * Add css and js files
 */
function user_filter_init() {
  drupal_add_css(drupal_get_path('module', 'user_filter') . '/user_filter.css');
  drupal_add_js(drupal_get_path('module', 'user_filter') . '/js/user_filter.js');
}